---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: harbor.pks.hms.hmsy.com/myfirstapp2/myapp1
          imagePullPolicy: Always
          ports: 
           - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: default
#   name: nodejs-app-svc
# spec:
#   ports:
#     - name: http
#       port: 80
#       protocol: TCP
#       targetPort: 8080
#   selector:
#     app: nodejs-app
#   type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nodejs-app-np
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nodejs-app
  type: NodePort
